### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by y-yagi** [y-yagi/tomato#1]
* [x] add config file 
* [ ] more clear timer
* [x] test
* [x] double start prevention
